package edu.mit.compilers.codegen.asm;

public enum OpCode {
	ADD, AND, DB, CMOVE, CMOVGE, CMOVG, CMOVLE, CMOVL, CMOVNE, CMP, CALL, ENTER, EXTERN, IDIV, IMUL, JE, JG, JGE, JL, JLE, JMP, JNE, LEA, LEAVE, MOV, NEG, NOP, POP, PUSH, RESW, RET, SHL, SAR, SUB, XCHG, XOR, GLOBAL;
}