package edu.mit.compilers.codegen.asm;

public enum OpCode {
	ADD, AND, DB, CMOVE, CMOVGE, CMOVG, CMOVLE, CMOVL, CMOVNE, CMP, CALL, CQO, ENTER, EXTERN, IDIV, IMUL, INT, JE, JG, JGE, JL, JLE, JMP, JNE, LEA, LEAVE, MOV, NEG, NOP, NOT, OR, POP, PUSH, RESW, RET, SHL, SAR, SUB, XCHG, XOR, GLOBAL, EQU, PUSHA, TIMES, DW;
}